nameOverride: "devspaces"
fullnameOverride: ""

namespace: openshift-operators


devspaces:
  namespace: openshift-operators
  subscription:
    channel: stable
    installPlanApproval: Automatic
    name: devspaces
    source: redhat-operators
    sourceNamespace: openshift-marketplace

checluster:
  namespace: devspaces
  name: devspaces
  namespaceTemplate: devspaces-<username>


argocd:
  enabled: true
  checluster:
    syncwave: "3"
  devspacesNamespace:
    syncwave: "1"
  devworkspaceTemplate:
    syncwave: "2"
  devworkspace:
    syncwave: "3"
  operator:
    syncwave: "-2"
