nameOverride: "devspaces"
fullnameOverride: ""

namespace: openshift-operators


devspaces:
  namespace: devspaces
  subscription:
    channel: stable
    installPlanApproval: Automatic
    name: devspaces
    source: redhat-operators
    sourceNamespace: openshift-marketplace

argocd:
  enabled: true
  operator:
    syncwave: "-2"

checluster:
  namespace: devspaces
  name: devspaces
  namespaceTemplate: devspaces-<username>
