nameOverride: "devspaces"
fullnameOverride: ""

namespace: openshift-operators


devspaces:
  subscription:
    channel: stable
    installPlanApproval: Automatic
    name: devspaces
    source: redhat-operators
    sourceNamespace: openshift-marketplace

argocd:
  enabled: true
  operator:
    syncwave: "-2"
